/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface SrSideDrawer {
    'headertitle': string;
    'open': () => Promise<void>;
    'opened': boolean;
  }
  interface SrStockPrice {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSrSideDrawerElement extends Components.SrSideDrawer, HTMLStencilElement {}
  var HTMLSrSideDrawerElement: {
    prototype: HTMLSrSideDrawerElement;
    new (): HTMLSrSideDrawerElement;
  };

  interface HTMLSrStockPriceElement extends Components.SrStockPrice, HTMLStencilElement {}
  var HTMLSrStockPriceElement: {
    prototype: HTMLSrStockPriceElement;
    new (): HTMLSrStockPriceElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'sr-side-drawer': HTMLSrSideDrawerElement;
    'sr-stock-price': HTMLSrStockPriceElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface SrSideDrawer extends JSXBase.HTMLAttributes<HTMLSrSideDrawerElement> {
    'headertitle'?: string;
    'opened'?: boolean;
  }
  interface SrStockPrice extends JSXBase.HTMLAttributes<HTMLSrStockPriceElement> {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'sr-side-drawer': SrSideDrawer;
    'sr-stock-price': SrStockPrice;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


